# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/feb44c7a-0102-40fd-9c84-19403677fe5a/transcription
Content-Type: application/json

{
  "prompt": "academia,estudar,prova"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "17b274b3-a112-448b-93c6-58438ddedc26",
  "temperature": 0.5,
  "prompt": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}